Tweaks to the UI text
PIVX-Project/PIVX-SPMT pull request #2
Opened 2018-05-23 14:05 UTC by lubinalubina

Various tweaks to the UI text.

2018-05-25 07:59 UTC, gpdionisio commented on src/hwdevice.py
>                  text += "locking script. Your signed transaction will not be validated by the network.\n"
Need to change both lines.
```
text = "Error: The hashes for the public key for the BIP32 path, and the UTXO locking script do not match."
text += "Your signed transaction will not be validated by the network.\n"
```

2018-05-25 08:06 UTC, gpdionisio commented on src/qt/gui_tabMain.py
> +        self.btn_details[name].setToolTip('Check status of "%s"' % name)
this is the magnifying glass. it is for *details*.
The next button is just for *status*

2018-05-25 08:10 UTC, gpdionisio commented on src/qt/gui_tabRewards.py
> +        label = QLabel("Total Balance")
`Total` could be misleading here.
One could think it's the total balance of a masternode (collater + rewards).

For example, creating 2 masternodes with the same collateral address is perfectly legal (provided they have different UTXOs).

2018-05-25 08:27 UTC, random-zebra requested changes
just few minor points

2018-05-26 13:14 UTC, lubinalubina commented
Updated all comments, and pushed changes

2018-05-26 16:41 UTC, random-zebra approved these changes

2018-05-26 16:41 UTC, merged