Update SPMT to Python 3.10 - PEP498 Literal String Interpolation
PIVX-Project/PIVX-SPMT pull request #60
Opened 2024-04-08 14:20 UTC by Liquid369

This pull request is updating the entire codebase to PEP 498 standards using fstrings. 

This PEP proposed a new syntax for formatting strings that is more concise, readable, and less error-prone compared to other string formatting methods like str.format() or % formatting. F-strings allow you to embed expressions inside string literals by prefixing the string with f or F and enclosing the expressions within curly braces {}.

I have updated every file to this standard and tested that our application is still functioning.

We have in this the added PyQt version bumped to `5.15.10`
Then we have also set wheel and setup tools to specific versions to avoid any of our dependancies with setup.py warnings on depreciation coming.

There is a small update in the spmt.py that is not the fstrings, but for testing purposes I needed to convert the splash sizing into an integer to load. This can be removed for a different fix, or whichever.

2024-04-15 00:03 UTC, Fuzzbawls requested changes
some changes needed, see inline comments.

Also, the `timeThis` function in `src/misc.py` needs updating as newer versions of python no longer have the `time.clock()` function:
```diff
Index: src/misc.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/misc.py b/src/misc.py
--- a/src/misc.py	
+++ b/src/misc.py	
@@ -491,9 +491,9 @@
 
 def timeThis(function, *args):
     try:
-        start = time.clock()
+        start = time.time()
         val = function(*args)
-        end = time.clock()
+        end = time.time()
         return val, (end - start)
     except Exception:
         return None, None

```

2024-04-15 00:03 UTC, Fuzzbawls commented on src/mainWindow.py
> +                myPopUp_sb(self, "info", 'SPMT - rpc check', f"{self.rpcStausMess}")
typo: `rpcStausMess` -> `rpcStatusMess`

2024-04-15 00:03 UTC, Fuzzbawls commented on src/tabGovernance.py
> +        self.ui.mnCountLabel.setText("Total MN Count: <em>{mnCount}</em>")
missing `f` before quoted string

2024-04-15 14:10 UTC, Liquid369 commented on src/mainWindow.py
> +                myPopUp_sb(self, "info", 'SPMT - rpc check', f"{self.rpcStausMess}")
Fixed and pushed

2024-04-15 14:10 UTC, Liquid369 commented on src/tabGovernance.py
> +        self.ui.mnCountLabel.setText("Total MN Count: <em>{mnCount}</em>")
fixed and pushed

2024-04-15 14:10 UTC, Liquid369 commented
Fixed all review suggestions. 

Thanks for those catches!

2024-04-16 07:57 UTC, Fuzzbawls approved these changes
ACK 7d6a69dbc15a88b6b75a83e55b820ea1f2d2b474

i've tested as much as I can using this PR with the changes suggested. without a dedicated test framework this is the best we can do.

2024-04-16 08:00 UTC, merged